package com.tairan.cloud.dao;

import com.tairan.cloud.model.Web;

public interface WebMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbggenerated
     */
    int insert(Web record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web
     *
     * @mbggenerated
     */
    int insertSelective(Web record);
}